# A deque is a list-like structure that's optimized to access elements on either end of the structure.
from collections import deque
# x = deque([1, 2, 3])
# print(x)
# x.appendleft(4)
# print(x)
# x.popleft()
# print(x)
# x.rotate()
# print(x)
# x.rotate(1)
# print(x)
# x.rotate()
# print(x)
# x.rotate(2)
# print(x)
# x.rotate(3)
# print(x)
x = list(range(10))
print(x)
print(deque(x, 5))
x = deque([30,40,50], maxlen=3)
print(x)
x.append(60)
print(x)
x.append(35)
print(x)
x.appendleft(70)
print(x)
